name: Project Submission
description: Submit a new project to the VinuChain Token List
title: "[Project] "
labels: ["submission", "project"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit a Project

        Use this form to submit a new project to the VinuChain Token List.

        **Please ensure:**
        - You represent the project officially
        - All information provided is accurate
        - You have authority to provide contact information

  - type: input
    id: project-id
    attributes:
      label: Project ID
      description: Lowercase, hyphenated identifier (will be the filename)
      placeholder: "my-awesome-project"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Project Name
      description: Official project or organization name
      placeholder: "My Awesome Project"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      description: Main project website URL
      placeholder: "https://example.com"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the project
      placeholder: "A decentralized finance protocol on VinuChain..."
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Email
      description: General contact email
      placeholder: "contact@example.com"
    validations:
      required: false

  - type: input
    id: security
    attributes:
      label: Security Contact Email
      description: Email for security vulnerability disclosure
      placeholder: "security@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Token Information
        If your project has a primary token, please provide the details below.

  - type: input
    id: token-address
    attributes:
      label: Token Address
      description: EIP55 checksummed token contract address
      placeholder: "0x..."
    validations:
      required: false

  - type: input
    id: token-symbol
    attributes:
      label: Token Symbol
      placeholder: "MYTOKEN"
    validations:
      required: false

  - type: input
    id: token-name
    attributes:
      label: Token Name
      placeholder: "My Token"
    validations:
      required: false

  - type: input
    id: token-decimals
    attributes:
      label: Token Decimals
      placeholder: "18"
    validations:
      required: false

  - type: input
    id: token-logo
    attributes:
      label: Token Logo URI
      description: URL to token logo image
      placeholder: "https://example.com/logo.png"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Social Links

  - type: input
    id: github
    attributes:
      label: GitHub
      placeholder: "https://github.com/example"
    validations:
      required: false

  - type: input
    id: twitter
    attributes:
      label: Twitter/X
      placeholder: "https://twitter.com/example"
    validations:
      required: false

  - type: input
    id: telegram
    attributes:
      label: Telegram
      placeholder: "https://t.me/example"
    validations:
      required: false

  - type: input
    id: discord
    attributes:
      label: Discord
      placeholder: "https://discord.gg/example"
    validations:
      required: false

  - type: input
    id: medium
    attributes:
      label: Medium
      placeholder: "https://medium.com/@example"
    validations:
      required: false

  - type: input
    id: coingecko
    attributes:
      label: CoinGecko
      placeholder: "https://www.coingecko.com/en/coins/example"
    validations:
      required: false

  - type: input
    id: coinmarketcap
    attributes:
      label: CoinMarketCap
      placeholder: "https://coinmarketcap.com/currencies/example"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I am authorized to represent this project
          required: true
        - label: All information provided is accurate and up-to-date
          required: true
        - label: I have permission to provide the contact information listed
          required: true
